/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ArticleId = bigint;
export interface BlogArticle {
  'id' : ArticleId,
  'title' : string,
  'body' : string,
  'tags' : Array<string>,
  'publishedAt' : Timestamp,
  'author' : string,
  'featuredImageUrl' : string,
  'excerpt' : string,
  'category' : string,
}
export interface ContactSubmission {
  'id' : bigint,
  'serviceType' : ServiceType,
  'name' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'message' : string,
}
export type ServiceType = string;
export type Timestamp = bigint;
export interface _SERVICE {
  'addBlogArticle' : ActorMethod<
    [string, string, string, string, Array<string>, Timestamp, string, string],
    ArticleId
  >,
  'getBlogArticleById' : ActorMethod<[ArticleId], [] | [BlogArticle]>,
  'getBlogArticles' : ActorMethod<[], Array<BlogArticle>>,
  'getContacts' : ActorMethod<[], Array<ContactSubmission>>,
  'searchBlogArticles' : ActorMethod<
    [string, [] | [string], [] | [string]],
    Array<BlogArticle>
  >,
  'submitContact' : ActorMethod<[string, string, ServiceType, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];