/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const ArticleId = IDL.Nat;
export const BlogArticle = IDL.Record({
  'id' : ArticleId,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : Timestamp,
  'author' : IDL.Text,
  'featuredImageUrl' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const ServiceType = IDL.Text;
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'serviceType' : ServiceType,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBlogArticle' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        Timestamp,
        IDL.Text,
        IDL.Text,
      ],
      [ArticleId],
      [],
    ),
  'getBlogArticleById' : IDL.Func(
      [ArticleId],
      [IDL.Opt(BlogArticle)],
      ['query'],
    ),
  'getBlogArticles' : IDL.Func([], [IDL.Vec(BlogArticle)], ['query']),
  'getContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
  'searchBlogArticles' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(BlogArticle)],
      ['query'],
    ),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, ServiceType, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const ArticleId = IDL.Nat;
  const BlogArticle = IDL.Record({
    'id' : ArticleId,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : Timestamp,
    'author' : IDL.Text,
    'featuredImageUrl' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const ServiceType = IDL.Text;
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'serviceType' : ServiceType,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'addBlogArticle' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          Timestamp,
          IDL.Text,
          IDL.Text,
        ],
        [ArticleId],
        [],
      ),
    'getBlogArticleById' : IDL.Func(
        [ArticleId],
        [IDL.Opt(BlogArticle)],
        ['query'],
      ),
    'getBlogArticles' : IDL.Func([], [IDL.Vec(BlogArticle)], ['query']),
    'getContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
    'searchBlogArticles' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(BlogArticle)],
        ['query'],
      ),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, ServiceType, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };